### ISSUE TITLE
Refactor WORKING branch to align with CSD01 - Delete Draft Spec from PUBLISHED

### ISSUE THREAD

**Issue by Vasileios-Mavroeidis** [oasis-tcs/openc2-ap-pf#12]
Our working branch never reflected the changes made / content added (i assume by OASIS administration?) in CSDO1 available here: https://docs.oasis-open.org/openc2/ap-pf/v1.0/

In addition to that, we have made (accepted/merged) some changes: https://github.com/oasis-tcs/openc2-ap-pf/pull/9

We need to refactor the branch. The steps are the following.
1. I'll update “Working” using the md from https://docs.oasis-open.org/openc2/ap-pf/v1.0/
2. I'll create a pull request based on https://github.com/oasis-tcs/openc2-ap-pf/pull/9 This is the work we have done after having CSD01 approved.
3. Delete oc2pf.md from “Published”

**Comment by dlemire60** [comment]
The OASIS viewpoint is that aside from the abstract they own the frontmatter of the document, everything prior to the Table of Contents. Sometimes they make other tweaks to the document internals to address publishing issues (e.g., they might fix a broken internal cross-reference link), and they _very_ much appreciate it if the editors capture such OASIS changes into the working copy so that they don't need to repeat those actions every time they publish an updated version.

**Comment by Vasileios-Mavroeidis** [comment]
Corrective actions performed: https://github.com/oasis-tcs/openc2-ap-pf/pull/13
